version: '3.7'

services:
  backend:
    container_name: apiserver
    image: 
    ports: 
      - 8000:8000
  database:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    name: postgres-db
