name: Test FastAPI Application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ${{github.workspace}}/backend
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-ver: [3.8]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-ver}}
      # Perma-cache Poetry
      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v2.1.5
        with:
          path: ~/.poetry
          key: ci-poetry
      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        uses: abatilo/actions-poetry@master
        with:
          poetry-version: 1.1.2
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2.1.5
        with:
          path: ${{github.workspace}}/.venv
          key: ci-poetry-deps
      - name: Install project dependencies
        if: steps.cache-deps.cache-hit != 'true'
        run: |
          poetry config virtualenvs.in-project true
          poetry install
      - name: Run tests with Poetry
        run: |
          cd ..
          docker-compose up database
          poetry run pytest